# Generated by Django 3.0.8 on 2021-04-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_shared',
            name='document_number',
            field=models.CharField(max_length=10),
        ),
    ]
