# Generated by Django 3.0.8 on 2021-04-26 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_document_limit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='document_limit',
        ),
    ]
