# Generated by Django 3.0.8 on 2021-04-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_document_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_limit',
            name='remaining_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
