# Generated by Django 3.0.8 on 2021-04-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_document_limit_remaining_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_limit',
            name='remaining_limit',
            field=models.IntegerField(default=20),
        ),
    ]
