# Generated by Django 3.0.8 on 2021-04-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210426_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
