# Generated by Django 3.0.8 on 2021-05-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_shared',
            name='document_type',
            field=models.CharField(default='OLD', max_length=10),
        ),
    ]
