# Generated by Django 3.0.8 on 2021-05-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_document_shared_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_shared',
            name='document_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='document_shared',
            name='document_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
