# Generated by Django 3.0.8 on 2021-07-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_document_shared_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_under_maintenance', models.BooleanField(default=False)),
            ],
        ),
    ]
