# Generated by Django 3.0.8 on 2021-08-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_document_unnecessary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_data',
            name='serial_number',
            field=models.CharField(max_length=255),
        ),
    ]
